name: jbdj
favicon: null
layout_spectrum: 0.3419104623608291
typography_spectrum: 0.6076891005504876
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.2552553836721927
  lightness: 0.33485211757943034
  saturation: 0.5817915310617536
  rhythmicContrast: 0.08920828578993678
purpose: []
